Prepare the Dataset

In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [3]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [4]:
# train test split
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [5]:
# data scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [8]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [9]:
X_train

array([[-0.62022183, -1.05166514, -0.55754821, ..., -0.82699676,
        -0.26950715,  1.15656784],
       [ 1.48216789,  1.74001293,  1.46236744, ...,  1.11661546,
         0.58338792,  0.78345871],
       [-0.12503087,  1.29381167, -0.15222099, ...,  0.28416442,
         0.92390347, -0.27757039],
       ...,
       [ 0.93485156,  1.46434932,  0.88272851, ...,  0.91271861,
        -0.63411577, -0.25191913],
       [-0.63759696, -0.04946439, -0.66675555, ..., -0.69346732,
        -0.57789858, -0.22335297],
       [-0.49280428,  1.80075237, -0.42985964, ...,  0.48346209,
         0.51432109,  2.14180914]])

In [10]:
y_train

array([0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1])

In [11]:
# convert the numpy arrays to tensors
X_train_tensor = torch.from_numpy(X_train.astype(np.float32))
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [12]:
print("Features shape: ", X_train_tensor.shape)
print("Label shape: ", y_train_tensor.shape)

Features shape:  torch.Size([455, 30])
Label shape:  torch.Size([455])

Make Custom Dataset Class for Pytorch

In [13]:
from torch.utils.data import Dataset, DataLoader

In [14]:
class CustomDataset(Dataset):
    def __init__ (self, features, labels):
        self.features = features
        self.labels = labels
        
    def __len__(self):
        return self.features.shape[0]
        
    def __getitem__(self, index):
        return self.features[index], self.labels[index]

In [15]:
# train dataset and test dataset instance
train_dataset = CustomDataset(X_train_tensor, y_train_tensor)
test_dataset = CustomDataset(X_test_tensor, y_test_tensor)

In [16]:
train_dataset[10]

(tensor([-0.8577, -1.0376, -0.8894, -0.7903,  0.2905, -0.8905, -0.8146, -0.5886,
         -0.8696,  0.5336, -0.6931,  1.0177, -0.7145, -0.4399,  2.5240, -0.2362,
         -0.5523,  0.6399,  1.2323,  0.3938, -1.0250, -1.4327, -1.0561, -0.8568,
         -0.4558, -1.1195, -1.1300, -1.0931, -1.5946, -0.6198]),
 tensor(0.))

Create Data Loader

In [17]:
# create data loader for both train and test dataset
train_loader = DataLoader(dataset=train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(dataset=test_dataset, batch_size=32, shuffle=True)

Defining The Model

In [18]:
import torch.nn as nn

In [22]:
# create the model class
class BreastCancerModel(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        # define the layers of the model
        self.layers = nn.Sequential(
            nn.Linear(num_features, 16),
            nn.ReLU(),
            nn.Linear(16, 8),
            nn.ReLU(),
            nn.Linear(8, 1),
            nn.Sigmoid()
        )

    def forward(self, features):
        return self.layers(features)

In [21]:
# parameters
learning_rate = 0.1
epochs = 25

In [24]:
# define the model
model = BreastCancerModel(X_train_tensor.shape[1])

# define the loss function
loss_fn = nn.BCELoss()

# define the optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

Training Pipeline

In [25]:
# define the training loop
def train_model(model, train_loader, loss_fn, optimizer, epochs):
    for epoch in range(epochs):
        for batch_features, batch_labels in train_loader:
            # forward pass
            y_pred = model(batch_features)

            # compute loss
            loss = loss_fn(y_pred, batch_labels.view(-1,1))

            # clear gradients
            optimizer.zero_grad()

            # backward pass
            loss.backward()

            # update parameters
            optimizer.step()

        # print loss in each epoch
        print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

In [26]:
# train the model
train_model(model, train_loader, loss_fn, optimizer, epochs)

Epoch: 1, Loss: 0.564412534236908
Epoch: 2, Loss: 0.357673704624176
Epoch: 3, Loss: 0.3176722526550293
Epoch: 4, Loss: 0.4409542977809906
Epoch: 5, Loss: 0.2095606029033661
Epoch: 6, Loss: 0.4805451035499573
Epoch: 7, Loss: 0.05302446708083153
Epoch: 8, Loss: 0.04696295037865639
Epoch: 9, Loss: 0.06859051436185837
Epoch: 10, Loss: 0.15155789256095886
Epoch: 11, Loss: 0.10954892635345459
Epoch: 12, Loss: 0.03295700624585152
Epoch: 13, Loss: 0.028256569057703018
Epoch: 14, Loss: 0.007270650006830692
Epoch: 15, Loss: 0.040077414363622665
Epoch: 16, Loss: 0.055354148149490356
Epoch: 17, Loss: 0.01711106114089489
Epoch: 18, Loss: 0.013380895368754864
Epoch: 19, Loss: 0.003369936952367425
Epoch: 20, Loss: 0.003548743436113
Epoch: 21, Loss: 0.01684141531586647
Epoch: 22, Loss: 0.10622513294219971
Epoch: 23, Loss: 0.014584586955606937
Epoch: 24, Loss: 0.005826628766953945
Epoch: 25, Loss: 0.01758839748799801

In [27]:
# Model evaluation using test_loader
model.eval()  # Set the model to evaluation mode
accuracy_list = []

with torch.no_grad():
    for batch_features, batch_labels in test_loader:
        # Forward pass
        y_pred = model(batch_features)
        y_pred = (y_pred > 0.8).float()  # Convert probabilities to binary predictions

        # Calculate accuracy for the current batch
        batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean().item()
        accuracy_list.append(batch_accuracy)

# Calculate overall accuracy
overall_accuracy = sum(accuracy_list) / len(accuracy_list)
print(f'Accuracy: {overall_accuracy:.4f}')

Accuracy: 0.9688

In [28]:
# predicting on a single sample from the test set
model.eval()
with torch.no_grad():
    sample_index = 0  # Change this index to test different samples
    sample_features, sample_label = test_dataset[sample_index]
    sample_features = sample_features.unsqueeze(0)  # Add batch dimension

    prediction = model(sample_features)
    predicted_class = (prediction > 0.8).float().item()  # Convert probability to binary prediction

    print(f'Sample Features: {sample_features}')
    print(f'True Label: {sample_label.item()}')
    print(f'Predicted Class: {predicted_class}')

Sample Features: tensor([[ 0.1414,  0.0440,  0.1204,  0.0418, -0.8930, -0.4980,  0.0030, -0.4998,
         -1.1989, -0.7853, -0.5277,  0.2385, -0.4142, -0.3545, -0.9166, -0.2787,
          0.0604, -0.4805, -0.7997, -0.5596,  0.0364,  0.4830,  0.0531, -0.0554,
         -1.0051,  0.0806,  0.5307, -0.2825, -0.6807, -0.5323]])
True Label: 0.0
Predicted Class: 0.0